<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>uuid</key>
	<string>1EEA33FD-AEAC-4C44-9EB6-D4D0D9E5C9CB</string>
	<key>fileTypes</key>
	<array>
		<string>chaml</string>
		<string>coffeehaml</string>
	</array>
	<key>name</key>
	<string>CoffeeHaml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#prologue</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-haml</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-html</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#doctype</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#element</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#implicit-div</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control-flow</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#output</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#filter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#text</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute-brace</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attributes.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attributes.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attribute.brace.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute-content</string>
				</dict>
			</array>
		</dict>
		<key>attribute-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#spread-jsx</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#spread-coffee</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-pair</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-shorthand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffeescript-expression</string>
				</dict>
			</array>
		</dict>
		<key>attribute-pair</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.coffeehaml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\w_-]+|"[^"]*"|'[^']*')\s*(:)(?!:)\s*</string>
			<key>name</key>
			<string>meta.attribute.pair.coffeehaml</string>
		</dict>
		<key>attribute-paren</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attributes.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attributes.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attribute.paren.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attribute-content</string>
				</dict>
			</array>
		</dict>
		<key>attribute-shorthand</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.shorthand.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=[\{,])[\s]*([\w$]+)(?=[,\}])</string>
			<key>name</key>
			<string>meta.attribute.shorthand.coffeehaml</string>
		</dict>
		<key>coffee-boolean</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|yes|no|on|off)\b</string>
			<key>name</key>
			<string>constant.language.boolean.coffeehaml</string>
		</dict>
		<key>coffee-bracket</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.begin.coffeehaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.curly.end.coffeehaml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.brace.curly.coffeehaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#coffeescript-expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.round.begin.coffeehaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.round.end.coffeehaml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.brace.round.coffeehaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#coffeescript-expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.begin.coffeehaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket.square.end.coffeehaml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.brace.square.coffeehaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#coffeescript-expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>coffee-comment</key>
		<dict>
			<key>match</key>
			<string>#(?![\{@]).*$</string>
			<key>name</key>
			<string>comment.line.number-sign.coffeehaml</string>
		</dict>
		<key>coffee-function</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.arrow.coffeehaml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(-&gt;|=&gt;)|\b(function)\b</string>
			<key>name</key>
			<string>meta.function.arrow.coffeehaml</string>
		</dict>
		<key>coffee-interpolation</key>
		<dict>
			<key>begin</key>
			<string>#\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interpolation.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interpolation.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.interpolation.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#coffeescript-expression</string>
				</dict>
			</array>
		</dict>
		<key>coffee-null</key>
		<dict>
			<key>match</key>
			<string>\b(null|undefined|this|Infinity|NaN)\b</string>
			<key>name</key>
			<string>constant.language.null.coffeehaml</string>
		</dict>
		<key>coffee-number</key>
		<dict>
			<key>match</key>
			<string>\b(0[xX][0-9a-fA-F]+|0[oO]?[0-7]+|0[bB][01]+|(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.coffeehaml</string>
		</dict>
		<key>coffee-operator</key>
		<dict>
			<key>match</key>
			<string>\b(and|or|not|is|isnt|instanceof|typeof|new|delete|of|in|then|when|do|by|own|unless|loop|break|continue|return|yield|await|throw|try|catch|finally|class|extends|super)\b|(\?\?|\.\.\.|\?\=|\.\.|\?\.?|:{2,3}|\|\||&amp;&amp;|[&lt;&gt;=!]==?|[-+*/%&amp;|^~]=?|[&lt;&gt;=!]=|[-+*/%&amp;|^~&lt;&gt;]=?)</string>
			<key>name</key>
			<string>keyword.operator.coffeehaml</string>
		</dict>
		<key>coffee-regex</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[=:(\[,!&amp;|?:;,\{\(])\s*(/{1,3})(?![/*])</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.regexp.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\2[gimuy]*</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.regexp.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.regexp.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.regexp.coffeehaml</string>
				</dict>
			</array>
		</dict>
		<key>coffee-splat</key>
		<dict>
			<key>match</key>
			<string>\.\.\.</string>
			<key>name</key>
			<string>keyword.operator.spread.coffeehaml</string>
		</dict>
		<key>coffee-string-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#coffee-interpolation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.coffeehaml</string>
				</dict>
			</array>
		</dict>
		<key>coffee-string-heredoc</key>
		<dict>
			<key>begin</key>
			<string>("""|''')</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\1</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.heredoc.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#coffee-interpolation</string>
				</dict>
			</array>
		</dict>
		<key>coffee-string-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.coffeehaml</string>
				</dict>
			</array>
		</dict>
		<key>coffee-string-template</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.coffeehaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.template.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#coffee-interpolation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.coffeehaml</string>
				</dict>
			</array>
		</dict>
		<key>coffee-import-keyword</key>
		<dict>
			<key>match</key>
			<string>\b(import|export|default|from|as|type)\b(?!\s*[=:])</string>
			<key>name</key>
			<string>keyword.control.import.coffeehaml</string>
		</dict>
		<key>coffee-variable</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z_$][\w$]*)\b</string>
			<key>name</key>
			<string>variable.other.coffeehaml</string>
		</dict>
		<key>coffeescript-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#coffee-string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-string-template</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-string-heredoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-interpolation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-null</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-splat</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-import-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffee-variable</string>
				</dict>
			</array>
		</dict>
		<key>comment-haml</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.coffeehaml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.haml.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)(-#)\s*(.*)$</string>
			<key>name</key>
			<string>comment.line.haml.coffeehaml</string>
		</dict>
		<key>comment-html</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.coffeehaml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.block.html.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)(/)\s*(.*)$</string>
			<key>name</key>
			<string>comment.block.html.coffeehaml</string>
		</dict>
		<key>control-flow</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(-)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.control.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.control.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|unless)\b</string>
					<key>name</key>
					<string>keyword.control.conditional.coffeehaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(for|while|do)\b</string>
					<key>name</key>
					<string>keyword.control.loop.coffeehaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(else|then|when|by|of|in)\b</string>
					<key>name</key>
					<string>keyword.control.flow.coffeehaml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#coffeescript-expression</string>
				</dict>
			</array>
		</dict>
		<key>doctype</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.doctype.coffeehaml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)(!!!)\s*(.*)$</string>
			<key>name</key>
			<string>meta.doctype.coffeehaml</string>
		</dict>
		<key>element</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(%)([\w-]+(?:\:[\w-]+)*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.coffeehaml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.tag.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#self-close</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-brace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-paren</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-output</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-text</string>
				</dict>
			</array>
		</dict>
		<key>filter</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(:)([\w-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.filter.coffeehaml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.filter.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.filter.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-text</string>
				</dict>
			</array>
		</dict>
		<key>implicit-div</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)([.#])([\w-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.tag.implicit.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-brace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-paren</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-output</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-text</string>
				</dict>
			</array>
		</dict>
		<key>inline-output</key>
		<dict>
			<key>begin</key>
			<string>(!=|=)(?!=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.output.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.output.inline.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#coffeescript-expression</string>
				</dict>
			</array>
		</dict>
		<key>inline-text</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^%#\-=/:!.{}()\\s]+</string>
					<key>name</key>
					<string>text.plain.coffeehaml</string>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.class.coffeehaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\.([\w-]+)</string>
					<key>name</key>
					<string>entity.name.tag.class.coffeehaml</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.id.coffeehaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#([\w-]+)</string>
					<key>name</key>
					<string>entity.name.tag.id.coffeehaml</string>
				</dict>
			</array>
		</dict>
		<key>output</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(!=|=)(?!=)(\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.output.coffeehaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.output.coffeehaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#coffeescript-expression</string>
				</dict>
			</array>
		</dict>
		<key>prologue</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#coffeescript-expression</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>^(import\b.*|export\b.*|const\b.*|let\b.*|var\b.*|function\b.*|class\b.*|@\w+.*|type\b.*|interface\b.*|enum\b.*)$</string>
			<key>name</key>
			<string>meta.prologue.coffeehaml</string>
		</dict>
		<key>self-close</key>
		<dict>
			<key>match</key>
			<string>/(?=\s|$)</string>
			<key>name</key>
			<string>keyword.operator.self-close.coffeehaml</string>
		</dict>
		<key>spread-coffee</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.spread.coffeehaml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.spread.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\w$]+)(\.\.\.)</string>
			<key>name</key>
			<string>meta.spread.coffee.coffeehaml</string>
		</dict>
		<key>spread-jsx</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.spread.coffeehaml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.spread.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\.\.\.)\s*([\w$]+)</string>
			<key>name</key>
			<string>meta.spread.jsx.coffeehaml</string>
		</dict>
		<key>text</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.plain.coffeehaml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)(\S.*)$</string>
			<key>name</key>
			<string>text.plain.coffeehaml</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.coffeehaml</string>
</dict>
</plist>